// Generated by https://colors.eva.design/
import colorsPalette from "./colors-palette.json";

const colorsAliases = {
  primary: colorsPalette["royal-blue"],
  success: colorsPalette["kelly-green"],
  danger: colorsPalette["ogre-odor"],
  warning: colorsPalette["vivid-orange-peel"],
};

const colors = {
  ...colorsPalette,
  ...colorsAliases,
  darkTheme: {
    surface: {
      100: "#242424",
      200: "#383838",
      300: "#4e4e4e",
      400: "#656565",
    },
  },
  lightTheme: {
    surface: {
      100: "#ffffff",
      200: "#f7f9fc",
      300: "#edf1f7",
      400: "#e4e9f7",
    },
  },
  surface: {
    100: "var(--colors-surface-100)",
    200: "var(--colors-surface-200)",
    300: "var(--colors-surface-300)",
    400: "var(--colors-surface-400)",
  },
  primaryMain: colorsAliases.primary[500],
  warningMain: colorsAliases.warning[500],
  successMain: colorsAliases.success[500],
  dangerMain: colorsAliases.danger[500],
};

export { colors };
